# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb33a198bf3dbf45ac092f354fa4ccb01e2fc4bba2cbf6e8be360d8560662a2e9ef5fa7871429a1516e421f125c4e4b78a173fc863f00c6de53a498ba5029ae

test:
  secret_key_base: d7e3e21c159a1d63b4702ca03c88b37a67de93979791db41fc906d957cfcd4fa019b57959f7e84a9619424dff451bb39b73cbbbefd32baff280f5e51eb100138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
